package at.fhv.journey.selenium.search;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FilterTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void filter() {
    driver.get("http://localhost:8080/Journey_war_exploded/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.linkText("DISCOVER")).click();
    driver.findElement(By.id("btn-search")).click();
    driver.findElement(By.id("drop-down-btn-fitness")).click();
    driver.findElement(By.linkText("Moderate")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.cssSelector(".hike-box:nth-child(1) .fitness-level-moderate")).click();
    driver.findElement(By.id("drop-down-btn-stamina")).click();
    driver.findElement(By.linkText("Intermediate")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.cssSelector(".noHikeText")).click();
    driver.findElement(By.id("drop-down-btn-stamina")).click();
    driver.findElement(By.linkText("Untrained")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.id("drop-down-btn-fitness")).click();
    driver.findElement(By.linkText("All options")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.id("drop-down-btn-stamina")).click();
    driver.findElement(By.linkText("Moderate")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.id("drop-down-btn-fitness")).click();
    driver.findElement(By.linkText("Intermediate")).click();
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.id("stamina-container-3")).click();
    driver.findElement(By.cssSelector(".fitnesslevel")).click();
    driver.findElement(By.cssSelector(".btn-danger")).click();
    {
      WebElement element = driver.findElement(By.id("search-input"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("search-input"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("search-input"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("search-input")).click();
    {
      WebElement element = driver.findElement(By.id("search-input"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("search-input"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
  }
}
