package at.fhv.journey.selenium.search;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class SearchTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void search() {
    driver.get("http://localhost:8080/Journey_war_exploded/search.jsp");
    driver.manage().window().setSize(new Dimension(1067, 726));
    driver.findElement(By.cssSelector(".search-container1")).click();
    driver.findElement(By.name("searchString")).click();
    driver.findElement(By.name("searchString")).click();
    driver.findElement(By.name("searchString")).sendKeys("Ludesch dorf");
    driver.findElement(By.name("searchString")).click();
    {
      String value = driver.findElement(By.name("searchString")).getAttribute("value");
      assertThat(value, is("Ludesch dorf"));
    }
    driver.findElement(By.cssSelector(".search-button")).click();
    driver.findElement(By.cssSelector(".col-md-8")).click();
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("Ludesch Dorfrundweg"));
  }


}
