package at.fhv.journey.selenium.search;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
public class SearchExistenceTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchExistence() {
    driver.get("http://localhost:8080/Journey_war_exploded/");
    driver.manage().window().setSize(new Dimension(816, 860));
    driver.findElement(By.linkText("DISCOVER")).click();
    driver.findElement(By.cssSelector("html")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".h2"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".search-container1"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.name("searchString")).click();
    {
      List<WebElement> elements = driver.findElements(By.name("searchString"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.id("btn-search"));
      assert(elements.size() > 0);
    }
  }
}
