package at.fhv.journey.Integration;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
public class IndexLinkingTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void indexLinking() {
    driver.get("http://localhost:8080/Journey_war_exploded/");
    driver.manage().window().setSize(new Dimension(816, 860));
    driver.findElement(By.linkText("DISCOVER")).click();
    driver.findElement(By.cssSelector(".logo")).click();
    driver.findElement(By.cssSelector("html")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("p"));
      assert(elements.size() > 0);
    }
  }
}
