package at.fhv.journey.Integration;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void search() {
    driver.get("http://localhost:8080/Journey_war_exploded/search.jsp");
    driver.manage().window().setSize(new Dimension(1067, 726));
    driver.findElement(By.cssSelector(".search-container1")).click();
    driver.findElement(By.name("searchString")).click();
    driver.findElement(By.name("searchString")).click();
    driver.findElement(By.name("searchString")).sendKeys("Ludesch");
    driver.findElement(By.name("searchString")).click();
    {
      String value = driver.findElement(By.name("searchString")).getAttribute("value");
      assertThat(value, is("Ludesch"));
    }
    driver.findElement(By.cssSelector(".search-button")).click();
    driver.findElement(By.cssSelector(".col-md-8")).click();
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("Ludesch Dorfrundweg"));
  }
}
