package at.fhv.journey.selenium.detail;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DetailPageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void detailPage() {
    WebDriverWait wait = new WebDriverWait(driver, java.time.Duration.ofSeconds(10));
    driver.get("http://localhost:8080/Journey_war_exploded/");
    driver.manage().window().setSize(new Dimension(1051, 798));
    driver.findElement(By.linkText("DISCOVER")).click();
    driver.findElement(By.name("searchString")).click();
    driver.findElement(By.name("searchString")).sendKeys("ludesch dorf");
    driver.findElement(By.name("searchString")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("19")).click();
    driver.findElement(By.cssSelector(".right-box > h1")).click();
    driver.findElement(By.cssSelector(".description > h1")).click();
    driver.findElement(By.cssSelector(".stats:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".stats:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".stats:nth-child(4)")).click();
    js.executeScript("window.scrollTo(0,688.7999877929688)");
    driver.findElement(By.linkText("Back")).click();
  }
}
